### ISSUE TITLE
Problem when output (filtered) is empty

### ISSUE THREAD

**Issue by fmalmeida** [ntoda03/NLGenomeSweeper#7]
Hi,

First of all congratulations on developing such nice tool.

I am currently facing a problem that is:

```bash
Filtering for presence of LRRs...
Traceback (most recent call last):
  File "/opt/NLGenomeSweeper-master/NLGenomeSweeper", line 302, in <module>
    main(sys.argv[1:])
  File "/opt/NLGenomeSweeper-master/NLGenomeSweeper", line 298, in main
    run_interproscan(program_dir, args.outdir + nlg_folder, args.t)
  File "/opt/NLGenomeSweeper-master/NLGenomeSweeper", line 196, in run_interproscan
    shell=True, check=True)
  File "/miniconda/envs/NLGenomeSweeper/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '/opt/NLGenomeSweeper-master/scripts/region_interproscan.sh ./NLGenomeSweeper/02_domain_identification/ 10 /opt/NLGenomeSweeper-master/' returned non-zero exit status 1.
```

It breaks on the "Filtering step". I have seen the temporary outputs and it seems to raise this error because no candidates have passed the filter (The filtered bed is blank). I believe, instead of raising the error, the pipeline should output a blank result.

What do you think?

Felipe.

**Comment by ntoda03** [comment]
Hi! The filtering step work with empty files as long as they exist, which they always should. I've added some upstream checks but I don't see any way that step could fail. If you're still interested in this or have example files let me know.

**Comment by fmalmeida** [comment]
Hello there!
Well, unfortunately I do not recall with which data this has happened. I'm still interested on it but don't know exactly how to help now. For now I have created a rule in my pipeline to ignore this error and create an empty final result ... But I don't believe is the best option.

Maybe if we use a contig that we know does not have any candidate and would therefore not generate results it can act as an example dataset for this?

**Comment by Wang-Mengda** [comment]
I have this problem, too. Do you have any solution ?
